# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 669)
        MainWindow.setMaximumSize(QtCore.QSize(1024, 768))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(140, 410, 711, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.test_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.test_btn.setObjectName("test_btn")
        self.gridLayout.addWidget(self.test_btn, 2, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.gridLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 0, 1, 1, 1)
        self.quitbtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.quitbtn.setObjectName("quitbtn")
        self.gridLayout.addWidget(self.quitbtn, 3, 1, 1, 1)
        self.TFpic_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.TFpic_btn.setObjectName("TFpic_btn")
        self.gridLayout.addWidget(self.TFpic_btn, 3, 0, 1, 1)
        self.Mypic_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Mypic_btn.setObjectName("Mypic_btn")
        self.gridLayout.addWidget(self.Mypic_btn, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralWidget)
        self.frame.setGeometry(QtCore.QRect(140, 30, 351, 361))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.graphicsView = QtWidgets.QGraphicsView(self.frame)
        self.graphicsView.setGeometry(QtCore.QRect(10, 10, 331, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.frame_2 = QtWidgets.QFrame(self.centralWidget)
        self.frame_2.setGeometry(QtCore.QRect(500, 30, 351, 361))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.tableView = QtWidgets.QTableView(self.frame_2)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 331, 341))
        self.tableView.setObjectName("tableView")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(290, 10, 67, 17))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(640, 10, 67, 17))
        self.label_3.setObjectName("label_3")
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setGeometry(QtCore.QRect(140, 400, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.debuglabel = QtWidgets.QLabel(self.centralWidget)
        self.debuglabel.setGeometry(QtCore.QRect(140, 570, 711, 17))
        self.debuglabel.setObjectName("debuglabel")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 28))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionFile_F = QtWidgets.QAction(MainWindow)
        self.actionFile_F.setObjectName("actionFile_F")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen_O = QtWidgets.QAction(MainWindow)
        self.actionOpen_O.setObjectName("actionOpen_O")
        self.actionExit_E = QtWidgets.QAction(MainWindow)
        self.actionExit_E.setObjectName("actionExit_E")
        self.menuFile.addAction(self.actionFile_F)
        self.menuFile.addAction(self.actionOpen_O)
        self.menuFile.addAction(self.actionExit_E)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.quitbtn.clicked.connect(MainWindow.close)
        self.actionExit_E.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.test_btn.setText(_translate("MainWindow", "识别数字"))
        self.quitbtn.setText(_translate("MainWindow", "Quit（退出程序）"))
        self.TFpic_btn.setText(_translate("MainWindow", "随机选择库图片"))
        self.Mypic_btn.setText(_translate("MainWindow", "选择手写图片"))
        self.label.setText(_translate("MainWindow", "识别结果："))
        self.label_2.setText(_translate("MainWindow", "图片"))
        self.label_3.setText(_translate("MainWindow", "存储数据"))
        self.debuglabel.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionFile_F.setText(_translate("MainWindow", "File(&F)"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen_O.setText(_translate("MainWindow", "Open(&O)"))
        self.actionExit_E.setText(_translate("MainWindow", "Exit(&E)"))

